web/django_test/pollster/polls/urls.py
from django.urls import path
from . import views

app_name='polls'
urlpatterns=[
    path('',views.index,name='index'), #This is basically a self-referencing route
    path('<int:question_id>',views.detail,name='detail'), #Passes the question's ID to get the Question & Choices
    path('<int:question_id>/results/',views.results,name='results') #Gets the question & displays its results
]

web/django_test/pollster/pollster/urls.py
from django.contrib import admin
from django.urls import path, include #'include' was added

urlpatterns = [
    path('polls/',include('polls.urls')), #Imports our polls/urls.py
    path('admin/', admin.site.urls),
]

web/django_test/pollster/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model): #To inherit the models methods.
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('Date Published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

web/django_test/pollster/polls/views.py
from django.shortcuts import render
from .models import Question,Choice

# Create your views here.

#Get questions and display them
def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[:5] #The - in front of pub_date makes it descending
    context={'latest_question_list':latest_question_list}
    return render(request,'polls/index.html',context)

#Show specific Question & Choices
def detail(request,question_id):
    try:
        question=Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'polls/results.html',{'question':question})

#Get Question & Display Results
def results(request,question_id):
    question=get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

web/django_test/pollster/templates/base.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <meta http-equiv='X-UA-Compatible' content='ie=edge'>
        <link rel='stylesheet' href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Pollster {%block title%}{%endblock%}</title>
    </head>
    <body>
        <div class='container'>
            <div class='row'>
                <div class='col-md-6 m-auto'>
                    {%block content%}{%endblock%}
                </div>
            </div>
        </div>
    </body>
</html>

web/django_test/pollster/templates/polls/detail.html
{%extends 'base.html'}

{%block content%}
<a class='btn btn-secondary btn-sm mb-3' href='{%url "polls:index"%}'>Back to Polls</a>
<h1 class='text-center mb-3'>{{question.question_text}}</h1>

{%if error_message%}
<p class='alert alert-danger'>
    <strong>{{error_message}}</strong>
</p>
{%endif%}

<form action='{%url "polls:vote" question.id%}' method='post'>
    {%csrf_token%}
</form>

web/django_test/pollster/templates/polls/index.html
{%extends 'base.html'%}

{%block content%}
    <h1 class='text-center mb-3'>Poll Questions</h1>
    {%if latest_question_list%}
        {%for question in latest_question_list%}
            <div class='card mb-3'>
                <div class='card-body'>
                    <p class='lead'>{{question.question_text}}</p>
                    <a href='{%url "polls:detail" question.id%}' class='btn btn-primary btn-sm'>Vote Now</a>
                    <a href='{%url "polls:results" question.id%}' class='btn btn-secondary btn-sm'>Results</a>
                </div>
            </div>
        {%endfor%}
    {%else%}
        <p>No polls available</p>
    {%endif%}
{%endblock%}